packages:
  - 'apps/*'
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
minimumReleaseAgeExclude:
  - '@expo/cli@56.1.14'
  - '@expo/fingerprint@0.19.4'
  - '@expo/inline-modules@0.0.11'
  - '@expo/prebuild-config@56.0.15'
  - '@expo/router-server@56.0.13'
  - expo-asset@56.0.16
  - expo-constants@56.0.17
  - expo-modules-autolinking@56.0.15
  - expo-modules-core@56.0.15
  - expo-modules-jsi@56.0.8
  - expo-server@56.0.5
  - expo@56.0.9
  - expo-notifications@56.0.16
